"""add outfit, image_style, speech_style

Revision ID: eea4c796ed0f
Revises: 8572ccfcce63
Create Date: 2026-08-15 09:21:47.386419

"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op


revision = 'eea4c796ed0f'
down_revision = '8572ccfcce63'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preferences', sa.Column('outfit', sa.Text(), nullable=True))
    op.add_column('user_preferences', sa.Column('image_style', sa.String(length=16), nullable=False))
    op.add_column('user_preferences', sa.Column('speech_style', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_preferences', 'speech_style')
    op.drop_column('user_preferences', 'image_style')
    op.drop_column('user_preferences', 'outfit')
    # ### end Alembic commands ###
